config/routes.rb
Rails.application.routes.draw do
  get "/about" => "home#about"
  root "home#index"

  get "/posts" => "posts#posts"

  get "/home/new" => "posts#new", as: :new_post
  post "/posts" => "posts#create", as: :post
  get "/posts/search" => "posts#search", as: :search_post
  get "/posts/:id" => "posts#show", as: :blog

  get "/posts/:id/edit" => "posts#edit", as: :edit_post
  patch "/posts/:id" => "posts#update"

  delete "/posts/:id" => "posts#destroy"

  resources :users
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :passwordresets, only: [:new, :create, :edit, :update]
    # get "/passwordresets/:reset_token/edit" => "passwordresets#edit"
    # patch "passwordresets/:reset_token" => "passwordresets#update", as: :reset_password
  # end
  resources :posts do
    resources :favourites, only: [:create, :destroy]
    resources :comments
    resources :ratings, only: [:create, :update, :destroy]
  end
  resources :favourites, only: [:index]


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :body, presence: true, uniqueness: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  def authenticate_user!
    redirect_to new_session_path, alert: "Please sign in" unless user_signed_in?
  end
  def index
    @comments = Comment.order("created_at")
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find params[:id]
  end

  def create
    @post = Post.find params[:post_id]
    comment_params = params.require(:comment).permit(:body)
    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to blog_path(@post), notice: "Comment saved"
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find params[:id]
    @post = @comment.post
  end

  def update
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
    comment_params = params.require(:comment).permit(:body)
    if @comment.update comment_params
      redirect_to blog_path(@post)
    else
      redirect_to edit_post_comment_path(@post, @comment)
    end
  end

  def destroy
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to blog_path(@post), notice: "Comment deleted"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for [@post, @comment] do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>
<h2><%= link_to "New Comment", new_comment_path %>
<hr>
<% @comments.each do |comment| %>
  <%= link_to comment.body, comment_path(comment) %>
  <hr>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for [@post, @comment] do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<p><%= @comment.body %></p><br>
<%= link_to "Edit", edit_comment_path(@comment) %>
<%= link_to "Delete", comment_path(@comment), method: :delete,
                                                data: {confirm: "Are you sure?"} %>