config/routes.rb
Rails.application.routes.draw do
  get "/about" => "home#about"
  root "home#index"

  get "/posts" => "posts#posts"

  get "/home/new" => "posts#new", as: :new_post
  post "/posts" => "posts#create", as: :post
  get "/posts/search" => "posts#search", as: :search_post
  get "/posts/:id" => "posts#show", as: :blog

  get "/posts/:id/edit" => "posts#edit", as: :edit_post
  patch "/posts/:id" => "posts#update"

  delete "/posts/:id" => "posts#destroy"

  resources :users
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :passwordresets, only: [:new, :create, :edit, :update]
    # get "/passwordresets/:reset_token/edit" => "passwordresets#edit"
    # patch "passwordresets/:reset_token" => "passwordresets#update", as: :reset_password
  # end
  resources :posts do
    resources :favourites, only: [:create, :destroy]
    resources :comments
    resources :ratings, only: [:create, :update, :destroy]
  end
  resources :favourites, only: [:index]


end

app/controllers/passwordresets_controller.rb
class PasswordresetsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user
      #email sent to the email address
      @user.set_token
      flash[:notice] = "Email has been sent"
      redirect_to root_path
    else
      flash[:alert] = "Email is not found"
      redirect_to new_passwordreset_path
    end
  end

  def edit
    @user = User.find_by_reset_token params[:id]
    if @user.password_reset_expired?
      redirect_to root_path, notice: "Link expired!"
    end
  end

  def update
    @user = User.find_by_reset_token params[:id]
    user_params = params.permit(:password, :password_confirmation)
    if @user.update user_params
      @user.unlock_account
      redirect_to root_path, notice: "Information updated!"
    else
      redirect_to edit_user_path(@user), notice: "aaa"
    end
  end

end

app/helpers/passwordresets_helper.rb
module PasswordresetsHelper
end

app/views/passwordresets/edit.html.erb
<%= form_tag passwordreset_path(params[:id]), method: :patch do %>
  <div>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div>
    <%= label_tag :password_confirmation %>
    <%= password_field_tag :password_confirmation %>
  </div>
  <%= submit_tag "Update" %>
<% end %>

app/views/passwordresets/new.html.erb
<h1>Forget Password</h1>
<%= form_tag passwordresets_path, method: :post do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>
  <%= submit_tag "Send Email" %>
<% end %>