config/routes.rb
Rails.application.routes.draw do
  get "/about" => "home#about"
  root "home#index"

  get "/posts" => "posts#posts"

  get "/home/new" => "posts#new", as: :new_post
  post "/posts" => "posts#create", as: :post
  get "/posts/search" => "posts#search", as: :search_post
  get "/posts/:id" => "posts#show", as: :blog

  get "/posts/:id/edit" => "posts#edit", as: :edit_post
  patch "/posts/:id" => "posts#update"

  delete "/posts/:id" => "posts#destroy"

  resources :users
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :passwordresets, only: [:new, :create, :edit, :update]
    # get "/passwordresets/:reset_token/edit" => "passwordresets#edit"
    # patch "passwordresets/:reset_token" => "passwordresets#update", as: :reset_password
  # end
  resources :posts do
    resources :favourites, only: [:create, :destroy]
    resources :comments
    resources :ratings, only: [:create, :update, :destroy]
  end
  resources :favourites, only: [:index]


end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :users, through: :favourites
  has_many :ratings, dependent: :destroy
  has_many :rating_users, through: :ratings, source: :user
  belongs_to :user
  validates :title, presence: true, uniqueness: true
  validate :title_length

  def self.search(content)
    where("title ILIKE :word OR body ILIKE :word", {word: "%#{content}%"} )
  end

  def favourite_for(user)
    favourites.find_by_user_id user
  end

  def favourite_by?(user)
    favourites.exists?(user: user)
  end

  def rated_by?(user)
    ratings.exists?(user: user)
  end

  def rate_for(user)
    ratings.find_by_user_id user
  end

  def rated_1_by?(user)
    rated_by?(user) && rate_for(user).star_count == 1
  end

  def rated_2_by?(user)
    rated_by?(user) && rate_for(user).star_count == 2
  end

  def rated_3_by?(user)
    rated_by?(user) && rate_for(user).star_count == 3
  end

  def rated_4_by?(user)
    rated_by?(user) && rate_for(user).star_count == 4
  end

  def rated_5_by?(user)
    rated_by?(user) && rate_for(user).star_count == 5
  end

  private

  def title_length
    if title.length < 7
      errors.add(:title, "Title length must be longer than 7 chars")
    end
  end

  def body_snippet
    body.length > 100 ? body[0...100] + "..." : body
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  def authenticate_user!
    redirect_to new_session_path, alert: "Please sign in" unless user_signed_in?
  end
  def posts
    @posts = Post.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find params[:id]
    @comment = Comment.new
  end

  def create
    post_params = params.require(:post).permit(:title, :body)
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to blog_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    post_params = params.require(:post).permit(:title, :body)
    if @post.update post_params
      redirect_to blog_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  def search
    if params[:search]
      # @posts = Post.all.search(params[:search][0])
      @posts = Post.all.search(params[:search][0]).paginate(:page => params[:page], :per_page => 10)
    else
      # @posts = Post.all
      @posts = Post.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def current_user_rate
    @post.rate_for(current_user)
  end
  helper_method :current_user_rate

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= @post.errors.full_messages.join(", ") %>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= @post.errors.full_messages.join(", ") %>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.collection_select :category_id, Category.all, :id, :title %>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/posts.html.erb
<h1>Posts</h1>
<%= form_tag search_post_path, method: :get do %>
  <p>
    <%= text_field :search, params[:search] %>
    <%= submit_tag "Search", name: :nil %>
  </p>
<% end %>
<div id="new-post"><%= link_to "New Post", new_post_path %></div>
<hr>
<% @posts.each do |post| %>
  <%= link_to post.title, blog_path(post) %>
  <hr>
<% end %>
<%= will_paginate @posts %>

app/views/posts/search.html.erb
<h1>Search</h1>
<hr>
<% @posts.each do |post| %>
  <%= link_to post.title, blog_path(post) %>
  <!-- <%= post %> -->
  <hr>
<% end %>
<%= will_paginate @posts %>

app/views/posts/show.html.erb
<h1><%= @post.title.titleize %></h1>
<div class="post-body">
<p><%= @post.body %></p>
<p>Created by: <%= @post.user.first_name if @post.user %></p>
<% if @post.rated_1_by?(current_user) %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate), method: :delete %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 2}), method: :patch %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 3}), method: :patch %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 4}), method: :patch %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 5}), method: :patch %>
<% elsif @post.rated_2_by?(current_user) %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 1}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate), method: :delete %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 3}), method: :patch %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 4}), method: :patch %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 5}), method: :patch %>
<% elsif @post.rated_3_by?(current_user) %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 1}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 2}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate), method: :delete %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 4}), method: :patch %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 5}), method: :patch %>
<% elsif @post.rated_4_by?(current_user) %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 1}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 2}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 3}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate), method: :delete %>
  <%= link_to fa_icon("star-o"), post_rating_path(@post, current_user_rate, rating: {star_count: 5}), method: :patch %>
<% elsif @post.rated_5_by?(current_user) %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 1}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 2}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 3}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate, rating: {star_count: 4}), method: :patch %>
  <%= link_to fa_icon("star"), post_rating_path(@post, current_user_rate), method: :delete %>
<% else %>
  <%= link_to fa_icon("star-o"), post_ratings_path(@post, rating: {star_count: 1}), method: :post %>
  <%= link_to fa_icon("star-o"), post_ratings_path(@post, rating: {star_count: 2}), method: :post %>
  <%= link_to fa_icon("star-o"), post_ratings_path(@post, rating: {star_count: 3}), method: :post %>
  <%= link_to fa_icon("star-o"), post_ratings_path(@post, rating: {star_count: 4}), method: :post %>
  <%= link_to fa_icon("star-o"), post_ratings_path(@post, rating: {star_count: 5}), method: :post %>
<% end %>
<% if @post.favourite_by?(current_user) %>
  <%= link_to fa_icon("heart"), post_favourite_path(@post, @post.favourite_for(current_user)), method: :delete %>
<% else %>
  <%= link_to fa_icon("heart-o"), post_favourites_path(@post), method: :post %>
<% end %>
</div>
<% if can? :manage, @post %>
  <%= link_to "Edit", edit_post_path(@post) %>
  <%= link_to "Delete", blog_path(@post), method: :delete,
                                                data: {confirm: "Are you sure?"} %>
<% end %>
<hr>
<h2>Comments</h2>
<%= @post.errors.full_messages.join(",") %>
<%= form_for [@post, @comment] do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>
<hr>
<% @post.comments.each do |comment| %>
  <%= comment.body %>
  <% if can? :manage, comment %>
    <%= link_to "Edit", edit_post_comment_path(@post, comment) %>
    <%= link_to "Delete", post_comment_path(@post, comment), method: :delete,
                                                data: {confirm: "Are you sure?"} %>
  <% end %>
  <hr>
<% end %>